site_name: Prime Video

repo_name: '2021.2-Prime-video'
repo_url: 'https://github.com/Requisitos-de-Software/2021.2-Prime-video'

theme:
  name: material
  language: 'pt'

nav: 
  - Início: index.md
  - Planejamento:
    - Metodologias: planejamento/metodologias.md 
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Aplicativos analisados: planejamento/apps-analisados.md
    - Padrões: 
      - Políticas de Branch: padroes/branches.md
      - Políticas de commit: padroes/commits.md
      - Template para Documentação: padroes/template.md
  - Pré-rastreabilidade:
    - Rich Picture: pre_rastreabilidade/rich_picture.md
  - Elicitação:
    - Personas: pre_rastreabilidade/rich_picture.md
  - Apresentações:
    - Apresentação 1: elicitacao/personas.md

extra_css:
  - stylesheets/styles.css
